name: Smoke Tests

on:
  schedule:
    # Daily 8:30 AM IST
    - cron: '0 3 * * *'

  workflow_dispatch:

jobs:

  smoke:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clean Old Allure Results
        run: rm -rf allure-results allure-results-smoke allure-history-smoke

      - name: Run Smoke Tests
        run: npm run smoke
        continue-on-error: true

      - name: Prepare Smoke Allure Results
        if: always()
        run: |
          mkdir -p allure-results-smoke
          cp -r allure-results/* allure-results-smoke/ || true

      - name: Generate Smoke Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-smoke
          allure_history: allure-history-smoke
          keep_reports: 20

      - name: Deploy Smoke Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history-smoke
          destination_dir: smoke
