name: API Tests

on:
  schedule:
    - cron: '0 0 * * *' # 5:30 AM IST

  workflow_dispatch:

jobs:

  api:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run API Tests
        run: npm run api
        continue-on-error: true

      - name: Generate API Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history-api
          keep_reports: 20

      - name: Deploy API Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history-api
          destination_dir: api
